// Master country list — worldwide coverage. `slug` is the URL-safe name used in
// corridor paths (existing slugs must never change: they're live URLs).
// `demonym` is the adjective for its people ("Indian citizens") — used in
// headings/titles because that's how people actually search.
// Flags are derived from the ISO code (regional-indicator emoji).

export interface Country {
  iso: string; // ISO 3166-1 alpha-2
  name: string;
  slug: string;
  flag: string; // emoji
  demonym: string; // "Indian", "American", "British"…
}

const flagOf = (iso: string) =>
  String.fromCodePoint(...[...iso.toUpperCase()].map((c) => 0x1f1e6 + c.charCodeAt(0) - 65));

// [iso, name, slug, demonym]
const DATA: Array<[string, string, string, string]> = [
  ['AF', 'Afghanistan', 'afghanistan', 'Afghan'],
  ['AL', 'Albania', 'albania', 'Albanian'],
  ['DZ', 'Algeria', 'algeria', 'Algerian'],
  ['AD', 'Andorra', 'andorra', 'Andorran'],
  ['AO', 'Angola', 'angola', 'Angolan'],
  ['AG', 'Antigua and Barbuda', 'antigua-and-barbuda', 'Antiguan'],
  ['AR', 'Argentina', 'argentina', 'Argentine'],
  ['AM', 'Armenia', 'armenia', 'Armenian'],
  ['AU', 'Australia', 'australia', 'Australian'],
  ['AT', 'Austria', 'austria', 'Austrian'],
  ['AZ', 'Azerbaijan', 'azerbaijan', 'Azerbaijani'],
  ['BS', 'Bahamas', 'bahamas', 'Bahamian'],
  ['BH', 'Bahrain', 'bahrain', 'Bahraini'],
  ['BD', 'Bangladesh', 'bangladesh', 'Bangladeshi'],
  ['BB', 'Barbados', 'barbados', 'Barbadian'],
  ['BY', 'Belarus', 'belarus', 'Belarusian'],
  ['BE', 'Belgium', 'belgium', 'Belgian'],
  ['BZ', 'Belize', 'belize', 'Belizean'],
  ['BJ', 'Benin', 'benin', 'Beninese'],
  ['BT', 'Bhutan', 'bhutan', 'Bhutanese'],
  ['BO', 'Bolivia', 'bolivia', 'Bolivian'],
  ['BA', 'Bosnia and Herzegovina', 'bosnia-and-herzegovina', 'Bosnian'],
  ['BW', 'Botswana', 'botswana', 'Botswanan'],
  ['BR', 'Brazil', 'brazil', 'Brazilian'],
  ['BN', 'Brunei', 'brunei', 'Bruneian'],
  ['BG', 'Bulgaria', 'bulgaria', 'Bulgarian'],
  ['BF', 'Burkina Faso', 'burkina-faso', 'Burkinabe'],
  ['BI', 'Burundi', 'burundi', 'Burundian'],
  ['KH', 'Cambodia', 'cambodia', 'Cambodian'],
  ['CM', 'Cameroon', 'cameroon', 'Cameroonian'],
  ['CA', 'Canada', 'canada', 'Canadian'],
  ['CV', 'Cape Verde', 'cape-verde', 'Cape Verdean'],
  ['CF', 'Central African Republic', 'central-african-republic', 'Central African'],
  ['TD', 'Chad', 'chad', 'Chadian'],
  ['CL', 'Chile', 'chile', 'Chilean'],
  ['CN', 'China', 'china', 'Chinese'],
  ['CO', 'Colombia', 'colombia', 'Colombian'],
  ['KM', 'Comoros', 'comoros', 'Comorian'],
  ['CG', 'Republic of the Congo', 'republic-of-the-congo', 'Congolese'],
  ['CD', 'DR Congo', 'dr-congo', 'Congolese'],
  ['CR', 'Costa Rica', 'costa-rica', 'Costa Rican'],
  ['HR', 'Croatia', 'croatia', 'Croatian'],
  ['CU', 'Cuba', 'cuba', 'Cuban'],
  ['CY', 'Cyprus', 'cyprus', 'Cypriot'],
  ['CZ', 'Czech Republic', 'czech-republic', 'Czech'],
  ['DK', 'Denmark', 'denmark', 'Danish'],
  ['DJ', 'Djibouti', 'djibouti', 'Djiboutian'],
  ['DM', 'Dominica', 'dominica', 'Dominican'],
  ['DO', 'Dominican Republic', 'dominican-republic', 'Dominican'],
  ['EC', 'Ecuador', 'ecuador', 'Ecuadorian'],
  ['EG', 'Egypt', 'egypt', 'Egyptian'],
  ['SV', 'El Salvador', 'el-salvador', 'Salvadoran'],
  ['GQ', 'Equatorial Guinea', 'equatorial-guinea', 'Equatoguinean'],
  ['ER', 'Eritrea', 'eritrea', 'Eritrean'],
  ['EE', 'Estonia', 'estonia', 'Estonian'],
  ['SZ', 'Eswatini', 'eswatini', 'Swazi'],
  ['ET', 'Ethiopia', 'ethiopia', 'Ethiopian'],
  ['FJ', 'Fiji', 'fiji', 'Fijian'],
  ['FI', 'Finland', 'finland', 'Finnish'],
  ['FR', 'France', 'france', 'French'],
  ['GA', 'Gabon', 'gabon', 'Gabonese'],
  ['GM', 'Gambia', 'gambia', 'Gambian'],
  ['GE', 'Georgia', 'georgia', 'Georgian'],
  ['DE', 'Germany', 'germany', 'German'],
  ['GH', 'Ghana', 'ghana', 'Ghanaian'],
  ['GR', 'Greece', 'greece', 'Greek'],
  ['GD', 'Grenada', 'grenada', 'Grenadian'],
  ['GT', 'Guatemala', 'guatemala', 'Guatemalan'],
  ['GN', 'Guinea', 'guinea', 'Guinean'],
  ['GW', 'Guinea-Bissau', 'guinea-bissau', 'Bissau-Guinean'],
  ['GY', 'Guyana', 'guyana', 'Guyanese'],
  ['HT', 'Haiti', 'haiti', 'Haitian'],
  ['HN', 'Honduras', 'honduras', 'Honduran'],
  ['HK', 'Hong Kong', 'hong-kong', 'Hong Kong'],
  ['HU', 'Hungary', 'hungary', 'Hungarian'],
  ['IS', 'Iceland', 'iceland', 'Icelandic'],
  ['IN', 'India', 'india', 'Indian'],
  ['ID', 'Indonesia', 'indonesia', 'Indonesian'],
  ['IR', 'Iran', 'iran', 'Iranian'],
  ['IQ', 'Iraq', 'iraq', 'Iraqi'],
  ['IE', 'Ireland', 'ireland', 'Irish'],
  ['IL', 'Israel', 'israel', 'Israeli'],
  ['IT', 'Italy', 'italy', 'Italian'],
  ['CI', 'Ivory Coast', 'ivory-coast', 'Ivorian'],
  ['JM', 'Jamaica', 'jamaica', 'Jamaican'],
  ['JP', 'Japan', 'japan', 'Japanese'],
  ['JO', 'Jordan', 'jordan', 'Jordanian'],
  ['KZ', 'Kazakhstan', 'kazakhstan', 'Kazakhstani'],
  ['KE', 'Kenya', 'kenya', 'Kenyan'],
  ['KI', 'Kiribati', 'kiribati', 'Kiribati'],
  ['XK', 'Kosovo', 'kosovo', 'Kosovar'],
  ['KW', 'Kuwait', 'kuwait', 'Kuwaiti'],
  ['KG', 'Kyrgyzstan', 'kyrgyzstan', 'Kyrgyz'],
  ['LA', 'Laos', 'laos', 'Lao'],
  ['LV', 'Latvia', 'latvia', 'Latvian'],
  ['LB', 'Lebanon', 'lebanon', 'Lebanese'],
  ['LS', 'Lesotho', 'lesotho', 'Basotho'],
  ['LR', 'Liberia', 'liberia', 'Liberian'],
  ['LY', 'Libya', 'libya', 'Libyan'],
  ['LI', 'Liechtenstein', 'liechtenstein', 'Liechtenstein'],
  ['LT', 'Lithuania', 'lithuania', 'Lithuanian'],
  ['LU', 'Luxembourg', 'luxembourg', 'Luxembourgish'],
  ['MO', 'Macau', 'macau', 'Macanese'],
  ['MG', 'Madagascar', 'madagascar', 'Malagasy'],
  ['MW', 'Malawi', 'malawi', 'Malawian'],
  ['MY', 'Malaysia', 'malaysia', 'Malaysian'],
  ['MV', 'Maldives', 'maldives', 'Maldivian'],
  ['ML', 'Mali', 'mali', 'Malian'],
  ['MT', 'Malta', 'malta', 'Maltese'],
  ['MH', 'Marshall Islands', 'marshall-islands', 'Marshallese'],
  ['MR', 'Mauritania', 'mauritania', 'Mauritanian'],
  ['MU', 'Mauritius', 'mauritius', 'Mauritian'],
  ['MX', 'Mexico', 'mexico', 'Mexican'],
  ['FM', 'Micronesia', 'micronesia', 'Micronesian'],
  ['MD', 'Moldova', 'moldova', 'Moldovan'],
  ['MC', 'Monaco', 'monaco', 'Monegasque'],
  ['MN', 'Mongolia', 'mongolia', 'Mongolian'],
  ['ME', 'Montenegro', 'montenegro', 'Montenegrin'],
  ['MA', 'Morocco', 'morocco', 'Moroccan'],
  ['MZ', 'Mozambique', 'mozambique', 'Mozambican'],
  ['MM', 'Myanmar', 'myanmar', 'Myanmar'],
  ['NA', 'Namibia', 'namibia', 'Namibian'],
  ['NR', 'Nauru', 'nauru', 'Nauruan'],
  ['NP', 'Nepal', 'nepal', 'Nepali'],
  ['NL', 'Netherlands', 'netherlands', 'Dutch'],
  ['NZ', 'New Zealand', 'new-zealand', 'New Zealand'],
  ['NI', 'Nicaragua', 'nicaragua', 'Nicaraguan'],
  ['NE', 'Niger', 'niger', 'Nigerien'],
  ['NG', 'Nigeria', 'nigeria', 'Nigerian'],
  ['KP', 'North Korea', 'north-korea', 'North Korean'],
  ['MK', 'North Macedonia', 'north-macedonia', 'Macedonian'],
  ['NO', 'Norway', 'norway', 'Norwegian'],
  ['OM', 'Oman', 'oman', 'Omani'],
  ['PK', 'Pakistan', 'pakistan', 'Pakistani'],
  ['PW', 'Palau', 'palau', 'Palauan'],
  ['PS', 'Palestine', 'palestine', 'Palestinian'],
  ['PA', 'Panama', 'panama', 'Panamanian'],
  ['PG', 'Papua New Guinea', 'papua-new-guinea', 'Papua New Guinean'],
  ['PY', 'Paraguay', 'paraguay', 'Paraguayan'],
  ['PE', 'Peru', 'peru', 'Peruvian'],
  ['PH', 'Philippines', 'philippines', 'Filipino'],
  ['PL', 'Poland', 'poland', 'Polish'],
  ['PT', 'Portugal', 'portugal', 'Portuguese'],
  ['QA', 'Qatar', 'qatar', 'Qatari'],
  ['RO', 'Romania', 'romania', 'Romanian'],
  ['RU', 'Russia', 'russia', 'Russian'],
  ['RW', 'Rwanda', 'rwanda', 'Rwandan'],
  ['KN', 'Saint Kitts and Nevis', 'saint-kitts-and-nevis', 'Kittitian'],
  ['LC', 'Saint Lucia', 'saint-lucia', 'Saint Lucian'],
  ['VC', 'Saint Vincent and the Grenadines', 'saint-vincent-and-the-grenadines', 'Vincentian'],
  ['WS', 'Samoa', 'samoa', 'Samoan'],
  ['SM', 'San Marino', 'san-marino', 'Sammarinese'],
  ['ST', 'Sao Tome and Principe', 'sao-tome-and-principe', 'Sao Tomean'],
  ['SA', 'Saudi Arabia', 'saudi-arabia', 'Saudi'],
  ['SN', 'Senegal', 'senegal', 'Senegalese'],
  ['RS', 'Serbia', 'serbia', 'Serbian'],
  ['SC', 'Seychelles', 'seychelles', 'Seychellois'],
  ['SL', 'Sierra Leone', 'sierra-leone', 'Sierra Leonean'],
  ['SG', 'Singapore', 'singapore', 'Singaporean'],
  ['SK', 'Slovakia', 'slovakia', 'Slovak'],
  ['SI', 'Slovenia', 'slovenia', 'Slovenian'],
  ['SB', 'Solomon Islands', 'solomon-islands', 'Solomon Islander'],
  ['SO', 'Somalia', 'somalia', 'Somali'],
  ['ZA', 'South Africa', 'south-africa', 'South African'],
  ['KR', 'South Korea', 'south-korea', 'South Korean'],
  ['SS', 'South Sudan', 'south-sudan', 'South Sudanese'],
  ['ES', 'Spain', 'spain', 'Spanish'],
  ['LK', 'Sri Lanka', 'sri-lanka', 'Sri Lankan'],
  ['SD', 'Sudan', 'sudan', 'Sudanese'],
  ['SR', 'Suriname', 'suriname', 'Surinamese'],
  ['SE', 'Sweden', 'sweden', 'Swedish'],
  ['CH', 'Switzerland', 'switzerland', 'Swiss'],
  ['SY', 'Syria', 'syria', 'Syrian'],
  ['TW', 'Taiwan', 'taiwan', 'Taiwanese'],
  ['TJ', 'Tajikistan', 'tajikistan', 'Tajik'],
  ['TZ', 'Tanzania', 'tanzania', 'Tanzanian'],
  ['TH', 'Thailand', 'thailand', 'Thai'],
  ['TL', 'Timor-Leste', 'timor-leste', 'Timorese'],
  ['TG', 'Togo', 'togo', 'Togolese'],
  ['TO', 'Tonga', 'tonga', 'Tongan'],
  ['TT', 'Trinidad and Tobago', 'trinidad-and-tobago', 'Trinidadian'],
  ['TN', 'Tunisia', 'tunisia', 'Tunisian'],
  ['TR', 'Turkey', 'turkey', 'Turkish'],
  ['TM', 'Turkmenistan', 'turkmenistan', 'Turkmen'],
  ['TV', 'Tuvalu', 'tuvalu', 'Tuvaluan'],
  ['UG', 'Uganda', 'uganda', 'Ugandan'],
  ['UA', 'Ukraine', 'ukraine', 'Ukrainian'],
  ['AE', 'United Arab Emirates', 'united-arab-emirates', 'Emirati'],
  ['GB', 'United Kingdom', 'united-kingdom', 'British'],
  ['US', 'United States', 'united-states', 'American'],
  ['UY', 'Uruguay', 'uruguay', 'Uruguayan'],
  ['UZ', 'Uzbekistan', 'uzbekistan', 'Uzbek'],
  ['VU', 'Vanuatu', 'vanuatu', 'Vanuatuan'],
  ['VE', 'Venezuela', 'venezuela', 'Venezuelan'],
  ['VN', 'Vietnam', 'vietnam', 'Vietnamese'],
  ['YE', 'Yemen', 'yemen', 'Yemeni'],
  ['ZM', 'Zambia', 'zambia', 'Zambian'],
  ['ZW', 'Zimbabwe', 'zimbabwe', 'Zimbabwean'],
];

export const COUNTRIES: Country[] = DATA.map(([iso, name, slug, demonym]) => ({
  iso,
  name,
  slug,
  demonym,
  flag: flagOf(iso),
}));

const BY_SLUG = new Map(COUNTRIES.map((c) => [c.slug, c]));
const BY_ISO = new Map(COUNTRIES.map((c) => [c.iso, c]));

export const countryBySlug = (slug: string) => BY_SLUG.get(slug);
export const countryByIso = (iso: string) => BY_ISO.get(iso);
